### ISSUE TITLE
Double Bullet Typo

### ISSUE THREAD

**Issue by mpalermo73** [finopsfoundation/kpis#1]
Hey!

There's a needless double bullet typo on line 40

```* * % taggable items tagged```

It should only be one asterisk.

```* % taggable items tagged```

Since it don't have write access to the `kpis` repo, I'm just opening this issue instead of GitHub's _super long_ way around of making a pull request.  If you'd rather me make a PR then open this issue, I can do that too though!

M.

**Comment by mfulleratlassian** [comment]
Thanks, I have corrected this.
